spring.datasource.url=jdbc:sqlserver://DESKTOP-2BKV5O7\\INSTANCE2022;databaseName=patient_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#exposing ending points for actuators

management.endpoints.web.exposure.include=health,info

management.info.env.enabled=true

info.app.name=Patient Care Management System

info.app.version= 1.0.0

#configure server port 
server.port=8181